<?php
/**
 * Friend groups module class
 * @author: Raysmond
 */

class friend_groups_module extends RModule {
    public $access = array('group/detail/*');

    public function module_content(){
        $currentGroupId = Rays::app()->controller->getActionParams()[0];
        $friends = new FriendsGroup();
        $friends = $friends->getFriends($currentGroupId);
        if(count($friends)==0)
            return '';
        return $this->render('friend_groups',array('friends'=>$friends));
    }
}