<?php
class friend_users_module extends RModule {
    public $access = array('<front>', 'user/*', 'group/mygroups', 'message/*', 'ads/*', 'friend/myFriend', 'friend/myFriend?*');

    public function module_content() {
    	$user = Rays::user();
    	if ($user == null)
    		return null;
        $friends = new Friend();
        list($friends, $friNumber) = $friends->getFriends($user->id, 9);
        return $this->render('friend_users', array('friends' => $friends, 'friNumber' => $friNumber));
    }
}
