<?php
/**
 * Group categories module
 * @author: Raysmond
 */

class group_categories_module extends RModule{
    public $access = array('category/groups/*','group/find','group/find/*');

    public function module_content()
    {
        $categories = new Category();
        $categories->pid = '0';
        $categories = $categories->find();
        return $this->render('group_categories',array('title'=>$this->getName(),'categories'=>$categories));
    }
}