<?php

class posts_category_module extends RModule
{

    public $access = array("post/find", "post/find/*", "post/find?*");

    public function module_content()
    {
        return $this->render("posts_category",
            array(
                'categories' => (new Category())->find(0, 0, null, null, ["pid" => '0']),
                'id' => Rays::router()->getParams()[0]
            ));
    }
}