<?php

class user_panel_module extends RModule
{
    public $user = null;
    public $params;

    public function __construct($params = array())
    {
        if (isset($params['userId'])) {
            $this->user = User::get($params['userId']);
        }

        $this->params = $params;
    }

    public function module_content()
    {
        $data = array(
            'user' => $this->user === null ? Rays::user() : $this->user,
            'isOwn' => (Rays::isLogin() && $this->user === null) || (Rays::isLogin() && $this->user !== null && Rays::user()->id == $this->user->id)
        );
        $data = array_merge($data, $this->params);
        return $this->render('user_panel', $data);
    }
}