<?php

class user_panel_module extends RModule
{
    public $user = null;

    public function __construct($params = array())
    {
        if (isset($params['userId'])) {
            $user = new User();
            if ($user->load($params['userId']) !== null) {
                $this->user = $user;
            }
        }
    }

    public function module_content()
    {
        $data = array(
            'user' => $this->user === null ? Rays::user() : $this->user,
            'isOwn' => (Rays::isLogin() && $this->user === null) || (Rays::isLogin() && $this->user !== null && Rays::user()->id == $this->user->id)
        );

        return $this->render('user_panel', $data);
    }
}