<?php
/**
 * Publish form module
 * @author: Raysmond
 */

class publish_form_module extends RModule
{
    public $access = array('user/home','user/myposts','group/view','group/build','post/new','post/edit','user/applyVIP','user/profile','user/profile/edit','user/edit','friend/myfriend','user/find','message/*','ads/*');

    public function __construct($params = array())
    {

    }

    public function module_content()
    {
        $data = array(
            'path'=>$this->getModulePath().'/../ckeditor',
            'initJs'=>$this->getModulePath()."/ckeditor_quick.js"
        );

        return $this->render('publish_form', $data);
    }
}
