<?php
/**
 * Created by PhpStorm.
 * User: songrenchu
 */
class active_groups_module extends RModule {

    public $access = array('category/groups/*', 'group/find', 'group/find*');

    /**
     * Override module_content method
     * @return string|void
     */
    public function module_content() {
        $cid = Rays::router()->getParams()[0];
        $p = [];
        $ids = [];
        if (isset($cid) && $cid !== null) {
            $p = ['categoryId' => [$cid]];
            $ids[] = $cid;
            $subCats = Category::get($cid)->children();
            foreach ($subCats as $sCat) {
                $ids[] = [$sCat->id];
                $p['categoryId'][] = $sCat->id;
            }
        }
        $groups = array();
        if (empty($ids))
            $groups = Group::find()->order_desc("memberCount")->range(0,5);
        else
            $groups = Group::find()->order_desc("memberCount")->where("categoryId",$ids)->range(0,5);

        return $this->render('active_groups',['groups'=>$groups]);
    }
}