<?php
/**
 * Created by PhpStorm.
 * User: songrenchu
 */
class active_groups_module extends RModule {

    public $access = array('category/groups/*', 'group/find', 'group/find*');

    /**
     * Override module_content method
     * @return string|void
     */
    public function module_content() {
        $cid = Rays::router()->getParams()[0];
        $p = [];
        if (isset($cid) && $cid !== null) {
            $p = ['categoryId' => [$cid]];
            foreach ((new Category())->load($cid)->children() as $sCat) {
                $p['categoryId'][] = $sCat->id;
            }
        }
        $groups = new Group();
        $groups = $groups->find(0, 5, ['key' => $groups->columns['memberCount'], 'order' => 'desc'], [], $p);
        if (!count($groups)) {
            $groups = new Group();
            $groups = $groups->find(0, 5, ['key' => $groups->columns['memberCount'], 'order' => 'desc']);
        }
        return $this->render('active_groups',
            array(
                'groups'=>$groups,
            ));
    }
}