<?php
/**
 * Created by PhpStorm.
 * User: songrenchu
 */
class active_groups_module extends RModule {

    public $access = array('category/groups/*', 'group/find', 'group/find*');

    /**
     * Override module_content method
     * @return string|void
     */
    public function module_content() {
        $cid = Rays::router()->getParams()[0];

        $groups = array();
        if(isset($cid)&&is_numeric($cid)){
            $category = Category::get($cid);
            if ($category == null) {
                return array();
            }

            $query = Group::find()->join("category")->order_desc("memberCount");
            $whereIds = Group::$mapping["categoryId"] . " in(";
            $subs = $category->children();
            $count = count($subs);
            $i = 0;
            foreach ($subs as $sCat) {
                $cidList[] = $sCat->id;
                $whereIds .= $sCat->id;
                if (++$i < $count) $whereIds .= ',';
            }
            $whereIds .= ')';
            unset($subs);

            $query = $query->where($whereIds);
            $groups = $query->range(0, 5);
        }
        else{
            $groups = Group::find()->join("category")->order_desc("memberCount")->range(0,5);
        }

        return $this->render('active_groups',['groups'=>$groups]);
    }
}