<?php
/**
 * Group categories module
 *
 * @author: Raysmond, Renchu Song
 */

class group_categories_module extends RModule
{
    public $access = array('category/groups/*', 'group/find', 'group/find?*', 'group/find/*', 'category/new');

    public function module_content()
    {
        $data = array(
            'categories' => Category::find("pid","0")->all(),
            'cid' => [],
        );

        $cid = Rays::router()->getParams()[0];
        if (isset($cid) && $cid !== null) {
            $data['cid'] [] = $cid;
            $category = Category::get($cid);
            if ($category->pid != 0) {
                $data['cid'] [] = $category->pid;
            }
        }

        return $this->render('group_categories', $data);
    }
}