<?php
/**
 * Group categories module
 * @author: Raysmond
 */

class group_categories_module extends RModule{
    public $access = array('category/groups/*','group/find','group/find?*','group/find/*','category/new');

    public function module_content()
    {
        $categories = new Category();
        $categories = $categories->find(0,0,[],[],['pid' => 0]);
        $data = [
            'title'=>$this->getName(),
            'categories'=>$categories,
            'cid' => [],
        ];
        $cid = Rays::router()->getParams()[0];
        if (isset($cid) && $cid !== null) {
            $data['cid'] []= $cid;$category= (new Category())->load($cid);
            if ($category->pid != 0) {
                $data['cid'] []= $category->pid;
            }
        }

        return $this->render('group_categories',$data);
    }
}