<?php
/**
 * Group categories module
 * @author: Raysmond
 */

class group_categories_module extends RModule{
    public $access = array('category/groups/*','group/find','group/find?*','group/find/*','category/new');

    public function module_content()
    {
        $categories = new Category();
        $categories = $categories->find(0,0,[],[],['pid' => 0]);
        return $this->render('group_categories',array('title'=>$this->getName(),'categories'=>$categories));
    }
}