<?php
/**
 * Group users module class file
 * @author: Raysmond
 */

class group_users_module extends RModule{
    public $access = array('group/detail/*');

    public function module_content()
    {
        $params = Rays::app()->controller->getActionParams();
        $groupId = $params[0];
        $users = Group::getMembers($groupId,0,9,"joinTime","DESC");
        return $this->render('group_users',array('users'=>$users,'groupId'=>$groupId));
    }


}