<?php
/**
 * New users module file
 * @author: Raysmond
 */

class new_users_module extends RModule{
    public $access = array('<front>','site/*');
    
    /**
     * Override module_content method
     * @return string|void
     */
    public function module_content(){
        $content = '<div class="panel panel-info">'
            .'<div class="panel-heading"><h3 class="panel-title">New Users</h3></div>'
            .'<div class="panel-body">';
        $content .= "This is new users module<br/>";
        $users = $this->findNewUsers();
        foreach($users as $user){
            $content.= RHtmlHelper::linkAction('user',$user->name,'view',array('uid'=>$user->id))." ";
        }
        $content.='</div></div>';
        return $content;
    }

    public function findNewUsers(){
        $user = new User();
        return $user->find(10,0,array('key'=>'u_id','order'=>'desc'));
    }
}