<?php
/**
 * New users module file
 * @author: Raysmond
 */

class new_users_module extends RModule{

    //public $access = array('<front>','site/*','admin');

    // Both tow module_content() methods can return the content of this
    // this module. The first one returns the HTML directly and the Second
    // one return the HTML rendered by a view file.
    // They have the same effect actually
    
    /**
     * Override module_content method
     * @return string|void
     */
    /*
    public function module_content(){
        $content = '<div class="panel panel-info">'
            .'<div class="panel-heading"><h3 class="panel-title">New Users</h3></div>'
            .'<div class="panel-body">';
        $content .= "This is new users module<br/>";
        $users = $this->findNewUsers();
        foreach($users as $user){
            $content.= RHtmlHelper::linkAction('user',$user->name,'view',array('uid'=>$user->id))." ";
        }
        $content.='</div></div>';
        return $content;
    }
    */

    /**
     * Override module_content method
     * @return string|void
     */
    public function module_content(){
        return $this->render('new_users',array('users'=>$this->findNewUsers()));
    }

    public function findNewUsers(){
        $user = new User();
        return $user->find(0,9,array('key'=>'u_id','order'=>'desc'));
    }
}