<?php
/**
 * Group users module class file
 * @author: Raysmond
 */

class group_users_module extends RModule{
    public $access = array('group/detail/*');

    public function module_content()
    {
        $group = new Group();
        $group->id = Rays::app()->controller->getActionParams()[0];
        $users = $group->groupUsers(10,'join_time','desc');
        return $this->render('group_users',array('users'=>$users));
    }


}