<?php
/**
 * Group users module class file
 * @author: Raysmond
 */

class group_users_module extends RModule{
    public $access = array('group/detail/*');

    public function module_content()
    {
        $group = new Group();
        $params = Rays::app()->controller->getActionParams();
        $group->id = $params[0];
        $users = $group->groupUsers(9,'join_time','desc');
        return $this->render('group_users',array('users'=>$users,'groupId'=>$group->id));
    }


}