<?php
/**
 * Plus one rating module class file
 * @author: Raysmond
 * Date: 13-11-25
 */

class rating_plus_module extends RModule
{
    public $entityType = null;
    public $entityId = null;
    public $count = null;

    public $buttonClass = 'btn btn-default btn-sm';

    private $url = 'rating/plus';

    private $plus = null;

    public function __construct($params = array())
    {
        parent::init($params);
        if (isset($params['entityType'])) {
            $this->entityType = $params['entityType'];
        }
        if (isset($params['entityId'])) {
            $this->entityId = $params['entityId'];
        }
        if (isset($params['count'])) {
            $this->count = $params['count'];
        }
        if (isset($params['buttonClass'])) {
            $this->buttonClass = $params['buttonClass'];
        }
    }

    public function module_content()
    {
        if($this->count===null){
            $this->loadPlus();
            $this->count = $this->getCount();
        }

        $counterId = $this->entityType . '_' . $this->entityId . '_counter';
        $actionUrl = RHtmlHelper::siteUrl($this->url);

        $this->addJs($this->getModulePath() . '/rating_plus.js');

        $html = '';
        if ($this->checkEntity()) {
            $html .= '<button type="button" '
                . 'onclick="javascript:plusEntity(\''
                . $actionUrl . '\',\'' . $this->entityType . '\',\'' . $this->entityId . '\')" '
                . 'class="rating-plus-button '.$this->buttonClass.'">'
                . '<span class="glyphicon glyphicon-star"></span> Plus '
                . '<span id="' . $counterId . '" class="badge">' . $this->count . '</span>'
                . '</button>';
        }
        return $html;
    }

    private function getCount()
    {
        $count = 0;
        if ($this->plus !== null) {
            $counter = $this->plus->getCounter();
            if ($counter !== null) {
                $count = $counter->value;
            }
        }
        return $count;
    }

    private function loadPlus()
    {
        $plus = new RatingPlus($this->entityType, $this->entityId);
        $this->plus = $plus;
    }

    private function checkEntity()
    {
        if (isset($this->entityType) && isset($this->entityId)) {
            if (is_numeric($this->entityId))
                return true;
        }
        return false;
    }
} 